import type { ApprovalRequest, ApprovalRule } from "./approval-types";

// Typed local/mock approval requests for the Approval Center (no backend yet).
// Timestamps are fixed ISO strings so the demo is deterministic.
export const approvalRequestsSeed: ApprovalRequest[] = [
  {
    id: "apr_001",
    title: "Refund pembayaran Rp 2.400.000",
    type: "refund",
    domain: "financial",
    requestedBy: { id: "u_fd1", name: "Clara Agustine", role: "Front Desk" },
    requestedAt: "2026-06-07T02:15:00Z",
    approver: { id: "u_owner", name: "Dinda Pramesti", role: "Owner" },
    relatedModule: "payments",
    relatedRoute: "/payments",
    relatedRecordId: "pay_8841",
    relatedRecordLabel: "Payment #8841 — Sarah Anindita",
    clientName: "Sarah Anindita",
    branch: "HOM Kemang",
    impactLabel: "Pengembalian dana ke klien",
    amountIdr: 2_400_000,
    risk: "high",
    status: "pending",
    waitingHours: 5,
    reason: "Klien batal mengikuti program karena pindah kota. Minta refund penuh.",
    evidence: [
      { id: "ev1", label: "Invoice #8841.pdf", type: "invoice" },
      { id: "ev2", label: "Chat permintaan refund.png", type: "screenshot" },
    ],
    riskCheck:
      "Refund di atas Rp 1.000.000 — wajib persetujuan Owner & pengecekan invoice terkait.",
    history: [
      { id: "h1", action: "created", actorName: "Clara Agustine", timestamp: "2026-06-07T02:15:00Z" },
    ],
  },
  {
    id: "apr_002",
    title: "Diskon 35% paket membership",
    type: "discount",
    domain: "financial",
    requestedBy: { id: "u_mkt", name: "Maya Lestari", role: "Marketing" },
    requestedAt: "2026-06-07T01:40:00Z",
    approver: { id: "u_owner", name: "Dinda Pramesti", role: "Owner" },
    relatedModule: "packages",
    relatedRoute: "/packages",
    relatedRecordId: "pkg_intro12",
    relatedRecordLabel: "Paket Intro 12 Sesi",
    branch: "HOM Senopati",
    impactLabel: "Penurunan harga 35% (>30% threshold)",
    amountIdr: 1_750_000,
    risk: "high",
    status: "pending",
    waitingHours: 7,
    reason: "Promo retensi untuk member yang hampir habis paketnya.",
    evidence: [{ id: "ev3", label: "Proposal promo.pdf", type: "document" }],
    riskCheck: "Diskon >30% memerlukan persetujuan Owner.",
    history: [
      { id: "h1", action: "created", actorName: "Maya Lestari", timestamp: "2026-06-07T01:40:00Z" },
    ],
  },
  {
    id: "apr_003",
    title: "Klaim reimbursement transport Rp 850.000",
    type: "reimbursement",
    domain: "financial",
    requestedBy: { id: "u_adm", name: "Raka Mahendra", role: "Admin" },
    requestedAt: "2026-06-05T08:00:00Z",
    approver: { id: "u_fin", name: "Finance Admin", role: "Finance Admin" },
    relatedModule: "financials",
    relatedRoute: "/financials",
    relatedRecordLabel: "Reimbursement transport workshop",
    branch: "HOM Kemang",
    impactLabel: "Penggantian biaya operasional",
    amountIdr: 850_000,
    risk: "medium",
    status: "need_more_info",
    waitingHours: 54,
    reason: "Transport untuk persiapan workshop akhir bulan.",
    evidence: [{ id: "ev4", label: "Struk transport.jpg", type: "receipt" }],
    riskCheck: "Reimbursement membutuhkan bukti struk yang lengkap.",
    history: [
      { id: "h1", action: "created", actorName: "Raka Mahendra", timestamp: "2026-06-05T08:00:00Z" },
      { id: "h2", action: "need_more_info", actorName: "Finance Admin", timestamp: "2026-06-05T10:00:00Z", note: "Mohon lampirkan struk yang lebih jelas." },
    ],
  },
  {
    id: "apr_004",
    title: "WhatsApp blast promo Juni (1.240 kontak)",
    type: "whatsapp_blast",
    domain: "marketing",
    requestedBy: { id: "u_mkt", name: "Maya Lestari", role: "Marketing" },
    requestedAt: "2026-06-07T03:00:00Z",
    approver: { id: "u_owner", name: "Dinda Pramesti", role: "Owner" },
    relatedModule: "marketing",
    relatedRecordLabel: "Campaign: Promo Reformer Juni",
    branch: "Semua Cabang",
    impactLabel: "Pesan ke 1.240 kontak",
    risk: "high",
    status: "pending",
    waitingHours: 3,
    reason: "Blast promo kelas Reformer untuk dorong booking pekan ini.",
    evidence: [{ id: "ev5", label: "Preview campaign", type: "campaign_preview" }],
    riskCheck: "Blast ke banyak kontak — perlu persetujuan Owner/Marketing Manager.",
    history: [
      { id: "h1", action: "created", actorName: "Maya Lestari", timestamp: "2026-06-07T03:00:00Z" },
    ],
  },
  {
    id: "apr_005",
    title: "Unlock session note (kasus klinis)",
    type: "note_unlock",
    domain: "clinical",
    requestedBy: { id: "u_prac", name: "Dewi Kartika", role: "Practitioner" },
    requestedAt: "2026-06-06T22:30:00Z",
    approver: { id: "u_clinical", name: "Clinical Lead", role: "Clinical Lead" },
    relatedModule: "clinical_cases",
    relatedRoute: "/clinical-cases",
    relatedRecordId: "case_3320",
    relatedRecordLabel: "Case #3320 — lower back",
    clientName: "Fajar Ramadhan",
    branch: "HOM Cilandak",
    impactLabel: "Buka kunci catatan klinis terkunci",
    risk: "critical",
    status: "escalated",
    waitingHours: 30,
    reason: "Perlu koreksi catatan sesi yang salah input sebelum follow-up.",
    evidence: [{ id: "ev6", label: "Alasan unlock.txt", type: "note" }],
    riskCheck:
      "Detail clinical bersifat sensitif. Hanya Clinical Lead atau Owner yang boleh approve.",
    sensitive: true,
    history: [
      { id: "h1", action: "created", actorName: "Dewi Kartika", timestamp: "2026-06-06T22:30:00Z" },
      { id: "h2", action: "escalated", actorName: "Admin", timestamp: "2026-06-07T04:00:00Z", note: "Eskalasi ke Clinical Lead." },
    ],
  },
  {
    id: "apr_006",
    title: "Export laporan finansial bulan Mei",
    type: "export_financial_report",
    domain: "admin_governance",
    requestedBy: { id: "u_fin", name: "Finance Admin", role: "Finance Admin" },
    requestedAt: "2026-06-07T00:10:00Z",
    approver: { id: "u_owner", name: "Dinda Pramesti", role: "Owner" },
    relatedModule: "financials",
    relatedRoute: "/financials",
    relatedRecordLabel: "Laporan Finansial Mei 2026",
    branch: "Semua Cabang",
    impactLabel: "Akses data finansial sensitif (export)",
    risk: "critical",
    status: "pending",
    waitingHours: 9,
    reason: "Untuk rekonsiliasi akuntan eksternal.",
    evidence: [{ id: "ev7", label: "Scope export.txt", type: "note" }],
    riskCheck: "Export data finansial sensitif — wajib disetujui Owner.",
    sensitive: true,
    history: [
      { id: "h1", action: "created", actorName: "Finance Admin", timestamp: "2026-06-07T00:10:00Z" },
    ],
  },
  {
    id: "apr_007",
    title: "Assign role Finance Admin ke Budi Santoso",
    type: "role_assignment",
    domain: "admin_governance",
    requestedBy: { id: "u_adm", name: "Raka Mahendra", role: "Admin" },
    requestedAt: "2026-06-07T01:00:00Z",
    approver: { id: "u_owner", name: "Dinda Pramesti", role: "Owner" },
    relatedModule: "roles",
    relatedRoute: "/settings/roles-permissions",
    relatedRecordLabel: "Role: finance_admin",
    branch: "HOM Kemang",
    impactLabel: "Pemberian akses data finansial",
    risk: "critical",
    status: "pending",
    waitingHours: 8,
    reason: "Budi akan menangani rekonsiliasi pembayaran cabang.",
    evidence: [{ id: "ev8", label: "Perubahan role (diff)", type: "diff" }],
    riskCheck: "Memberi akses data sensitif — harus disetujui Owner.",
    requiresSecondApproval: true,
    history: [
      { id: "h1", action: "created", actorName: "Raka Mahendra", timestamp: "2026-06-07T01:00:00Z" },
    ],
  },
  {
    id: "apr_008",
    title: "Hard-delete data klien duplikat",
    type: "hard_delete",
    domain: "admin_governance",
    requestedBy: { id: "u_adm", name: "Raka Mahendra", role: "Admin" },
    requestedAt: "2026-06-06T20:00:00Z",
    approver: { id: "u_owner", name: "Dinda Pramesti", role: "Owner" },
    relatedModule: "clients",
    relatedRoute: "/clients",
    relatedRecordId: "cli_dup_22",
    relatedRecordLabel: "Klien duplikat: Sarah A. (2 record)",
    branch: "HOM Kemang",
    impactLabel: "Penghapusan permanen data",
    risk: "critical",
    status: "pending",
    waitingHours: 36,
    reason: "Dua record klien ganda dari import lama.",
    evidence: [{ id: "ev9", label: "Bukti duplikat.png", type: "screenshot" }],
    riskCheck: "Aksi destruktif — butuh Owner + persetujuan kedua.",
    requiresSecondApproval: true,
    history: [
      { id: "h1", action: "created", actorName: "Raka Mahendra", timestamp: "2026-06-06T20:00:00Z" },
    ],
  },
  {
    id: "apr_009",
    title: "Freeze membership 1 bulan",
    type: "membership_freeze",
    domain: "client_membership",
    requestedBy: { id: "u_fd1", name: "Clara Agustine", role: "Front Desk" },
    requestedAt: "2026-06-07T02:50:00Z",
    approver: { id: "u_mgr", name: "Sarah Anindita", role: "Manager" },
    relatedModule: "client-packages",
    relatedRoute: "/client-packages",
    relatedRecordLabel: "Membership Yoga Pratama",
    clientName: "Yoga Pratama",
    branch: "HOM Senopati",
    impactLabel: "Penjedaan langganan (revenue tertunda)",
    risk: "low",
    status: "pending",
    waitingHours: 4,
    reason: "Klien cuti kerja ke luar kota 1 bulan.",
    evidence: [{ id: "ev10", label: "Permintaan freeze.txt", type: "note" }],
    riskCheck: "Freeze menunda revenue — perlu persetujuan Manager.",
    history: [
      { id: "h1", action: "created", actorName: "Clara Agustine", timestamp: "2026-06-07T02:50:00Z" },
    ],
  },
  {
    id: "apr_010",
    title: "Cancel membership + refund prorata Rp 1.100.000",
    type: "membership_cancel",
    domain: "client_membership",
    requestedBy: { id: "u_fd2", name: "Rizky Amanda", role: "Front Desk" },
    requestedAt: "2026-06-06T18:00:00Z",
    approver: { id: "u_owner", name: "Dinda Pramesti", role: "Owner" },
    relatedModule: "client-packages",
    relatedRoute: "/client-packages",
    relatedRecordLabel: "Membership Maya Lestari",
    clientName: "Maya Lestari",
    branch: "HOM Cilandak",
    impactLabel: "Terminasi + refund prorata",
    amountIdr: 1_100_000,
    risk: "medium",
    status: "pending",
    waitingHours: 38,
    reason: "Klien cedera dan disarankan berhenti sementara waktu lama.",
    evidence: [{ id: "ev11", label: "Surat dokter.pdf", type: "document" }],
    riskCheck: "Refund prorata di atas Rp 1.000.000 — perlu persetujuan Owner.",
    history: [
      { id: "h1", action: "created", actorName: "Rizky Amanda", timestamp: "2026-06-06T18:00:00Z" },
    ],
  },
  {
    id: "apr_011",
    title: "Waive biaya no-show",
    type: "waive_no_show",
    domain: "booking",
    requestedBy: { id: "u_fd1", name: "Clara Agustine", role: "Front Desk" },
    requestedAt: "2026-06-06T12:00:00Z",
    approver: { id: "u_mgr", name: "Sarah Anindita", role: "Manager" },
    relatedModule: "appointments",
    relatedRoute: "/appointments",
    relatedRecordLabel: "Appointment #5521",
    clientName: "Fajar Ramadhan",
    branch: "HOM Kemang",
    impactLabel: "Pembebasan denda no-show",
    risk: "low",
    status: "approved",
    waitingHours: 2,
    reason: "Klien mengalami kecelakaan kecil, ada bukti.",
    evidence: [{ id: "ev12", label: "Bukti chat.png", type: "screenshot" }],
    riskCheck: "Waiver denda — perlu persetujuan Manager.",
    history: [
      { id: "h1", action: "created", actorName: "Clara Agustine", timestamp: "2026-06-06T12:00:00Z" },
      { id: "h2", action: "approved", actorName: "Sarah Anindita", timestamp: "2026-06-06T14:00:00Z" },
    ],
  },
  {
    id: "apr_012",
    title: "Overbooking kelas Reformer 18:00 (+2)",
    type: "overbooking",
    domain: "booking",
    requestedBy: { id: "u_fd2", name: "Rizky Amanda", role: "Front Desk" },
    requestedAt: "2026-06-07T03:20:00Z",
    approver: { id: "u_mgr", name: "Sarah Anindita", role: "Manager" },
    relatedModule: "appointments",
    relatedRoute: "/appointments",
    relatedRecordLabel: "Kelas Reformer 18:00",
    branch: "HOM Senopati",
    impactLabel: "Melebihi kapasitas kelas",
    risk: "medium",
    status: "pending",
    waitingHours: 2,
    reason: "Permintaan tinggi, 2 klien VIP minta masuk waitlist.",
    evidence: [{ id: "ev13", label: "Waitlist.txt", type: "note" }],
    riskCheck: "Overbooking dapat menurunkan kualitas sesi — perlu persetujuan Manager.",
    history: [
      { id: "h1", action: "created", actorName: "Rizky Amanda", timestamp: "2026-06-07T03:20:00Z" },
    ],
  },
  {
    id: "apr_013",
    title: "Clearance PAR-Q sebelum program intensif",
    type: "parq_clearance",
    domain: "clinical",
    requestedBy: { id: "u_prac", name: "Dewi Kartika", role: "Practitioner" },
    requestedAt: "2026-06-07T01:10:00Z",
    approver: { id: "u_clinical", name: "Clinical Lead", role: "Clinical Lead" },
    relatedModule: "clinical_cases",
    relatedRoute: "/clinical-cases",
    relatedRecordLabel: "Screening kesehatan klien baru",
    clientName: "Budi Santoso",
    branch: "HOM Kemang",
    impactLabel: "Kelayakan klien untuk program berisiko",
    risk: "medium",
    status: "pending",
    waitingHours: 6,
    reason: "Klien punya riwayat tekanan darah, perlu clearance sebelum reformer intensif.",
    evidence: [{ id: "ev14", label: "Form PAR-Q.pdf", type: "document" }],
    riskCheck: "Detail klinis sensitif. Hanya Clinical Lead/Owner yang boleh approve.",
    sensitive: true,
    history: [
      { id: "h1", action: "created", actorName: "Dewi Kartika", timestamp: "2026-06-07T01:10:00Z" },
    ],
  },
  {
    id: "apr_014",
    title: "Onboarding practitioner baru (verifikasi sertifikat)",
    type: "practitioner_onboarding",
    domain: "team",
    requestedBy: { id: "u_adm", name: "Raka Mahendra", role: "Admin" },
    requestedAt: "2026-06-06T16:00:00Z",
    approver: { id: "u_owner", name: "Dinda Pramesti", role: "Owner" },
    relatedModule: "practitioners",
    relatedRoute: "/practitioners",
    relatedRecordLabel: "Practitioner: Andini (kandidat)",
    branch: "HOM Cilandak",
    impactLabel: "Aktivasi practitioner menangani klien",
    risk: "medium",
    status: "pending",
    waitingHours: 40,
    reason: "Verifikasi sertifikasi clinical pilates sebelum mulai mengajar.",
    evidence: [{ id: "ev15", label: "Sertifikat.pdf", type: "document" }],
    riskCheck: "Practitioner harus terverifikasi sebelum boleh menangani klien.",
    history: [
      { id: "h1", action: "created", actorName: "Raka Mahendra", timestamp: "2026-06-06T16:00:00Z" },
    ],
  },
  {
    id: "apr_015",
    title: "Payroll & komisi instruktur Juni",
    type: "payroll",
    domain: "financial",
    requestedBy: { id: "u_fin", name: "Finance Admin", role: "Finance Admin" },
    requestedAt: "2026-06-07T00:30:00Z",
    approver: { id: "u_owner", name: "Dinda Pramesti", role: "Owner" },
    relatedModule: "financials",
    relatedRoute: "/financials",
    relatedRecordLabel: "Payroll run Juni 2026",
    branch: "Semua Cabang",
    impactLabel: "Pembayaran gaji + komisi",
    amountIdr: 38_500_000,
    risk: "high",
    status: "pending",
    waitingHours: 9,
    reason: "Payroll bulanan + komisi kelas instruktur.",
    evidence: [{ id: "ev16", label: "Rekap payroll.xlsx", type: "document" }],
    riskCheck: "Pengeluaran besar — wajib persetujuan Owner sebelum dieksekusi.",
    history: [
      { id: "h1", action: "created", actorName: "Finance Admin", timestamp: "2026-06-07T00:30:00Z" },
    ],
  },
];

export const approvalRulesSeed: ApprovalRule[] = [
  { id: "r1", actionType: "Refund (any amount)", condition: "Refund nominal berapa pun", approverRole: "Manager", risk: "medium", isActive: true },
  { id: "r2", actionType: "Refund > Rp 1.000.000", condition: "Refund di atas Rp 1.000.000", approverRole: "Owner", risk: "high", isActive: true },
  { id: "r3", actionType: "Discount > 15%", condition: "Diskon antara 15%–30%", approverRole: "Manager", risk: "medium", isActive: true },
  { id: "r4", actionType: "Discount > 30%", condition: "Diskon di atas 30%", approverRole: "Owner", risk: "high", isActive: true },
  { id: "r5", actionType: "Unlock session note", condition: "Buka kunci catatan klinis", approverRole: "Clinical Lead", risk: "critical", isActive: true },
  { id: "r6", actionType: "WhatsApp blast", condition: "Blast pesan massal", approverRole: "Owner / Marketing Manager", risk: "high", isActive: true },
  { id: "r7", actionType: "Reimbursement", condition: "Klaim penggantian biaya", approverRole: "Finance Admin / Owner", risk: "medium", isActive: true },
  { id: "r8", actionType: "Publish Knowledge", condition: "Publikasi artikel knowledge", approverRole: "Studio Director", risk: "medium", isActive: true },
  { id: "r9", actionType: "Export financial report", condition: "Export laporan finansial", approverRole: "Owner", risk: "critical", isActive: true },
  { id: "r10", actionType: "Client data export", condition: "Export data klien", approverRole: "Owner", risk: "critical", isActive: true },
  { id: "r11", actionType: "Assign high-level role", condition: "Pemberian role akses tinggi", approverRole: "Owner", risk: "critical", isActive: true },
  { id: "r12", actionType: "Hard-delete data", condition: "Hapus permanen data", approverRole: "Owner + persetujuan kedua", risk: "critical", isActive: true },
  { id: "r13", actionType: "Production integration", condition: "Koneksi integrasi production", approverRole: "Owner", risk: "critical", isActive: true },
  { id: "r14", actionType: "Branch opening/closing", condition: "Buka/tutup cabang", approverRole: "Owner", risk: "high", isActive: true },
];
