export const apiErrorCodes = [
  "VALIDATION_ERROR",
  "UNAUTHORIZED",
  "FORBIDDEN",
  "NOT_FOUND",
  "CONFLICT",
  "BUSINESS_RULE_FAILED",
  "EXTERNAL_SERVICE_FAILED",
  "AI_POLICY_BLOCKED",
  "RATE_LIMITED",
  "NOT_IMPLEMENTED",
  "INTERNAL_ERROR",
] as const;
